# Generated by Django 2.2.17 on 2021-03-10 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stormwind', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='date_posted',
            new_name='date_created',
        ),
    ]
