# Generated by Django 2.2.17 on 2021-03-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stormwind', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='category',
            field=models.CharField(default='Community', max_length=155),
        ),
    ]
