# Generated by Django 2.2.17 on 2021-03-12 08:06

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('stormwind', '0004_thread_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='category',
            field=models.CharField(max_length=155),
        ),
        migrations.AlterField(
            model_name='thread',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
