# Generated by Django 2.2.17 on 2021-03-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stormwind', '0005_auto_20210312_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='category',
            field=models.CharField(default='Community', max_length=155),
        ),
        migrations.AlterField(
            model_name='thread',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
