# Generated by Django 2.2.17 on 2021-03-12 08:50

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('stormwind', '0006_auto_20210312_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
