# Generated by Django 2.2.17 on 2021-04-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stormwind', '0010_auto_20210405_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='img',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
