# Generated by Django 2.2.17 on 2021-04-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stormwind', '0011_reply_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='img',
        ),
        migrations.AddField(
            model_name='reply',
            name='img_url',
            field=models.CharField(default='default.jpg', max_length=200),
        ),
    ]
