# Generated by Django 2.2.17 on 2021-04-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stormwind', '0012_auto_20210406_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='img_url',
            field=models.ImageField(upload_to=''),
        ),
    ]
